const { get_results } = require('./ia_gen');

(async () => {
  try {
    const resultado = await get_results('Escreva um resumo simples e direto do conteúdo da aula a seguir. O tom deve ser claro e acessível, considerando estudantes de graduação. Use formatação compatível com WhatsApp, seguindo estas regras: destaque títulos ou conceitos importantes em negrito, separe as ideias principais com quebras de linha curtas e não use tópicos nem listas longas. Conteúdo da aula: Aula: Informática na Educação – Introdução e Possibilidades. A informática na educação é o uso das tecnologias digitais para apoiar o processo de ensino e aprendizagem. Não se trata apenas de computadores, mas também de tablets, celulares e recursos online. Histórico. Nos anos 1980, os computadores começaram a ser usados em escolas, geralmente em laboratórios de informática. A ideia era ensinar o aluno a programar e a usar o computador como ferramenta de cálculo e escrita. Evolução. Com a internet, a informática na educação passou a incluir ambientes virtuais de aprendizagem (como Moodle e Google Classroom), uso de vídeos e jogos educativos. Hoje, fala-se também em inteligência artificial, realidade aumentada e realidade virtual aplicadas à sala de aula. Benefícios. Apoio à aprendizagem personalizada (cada aluno pode aprender no seu ritmo). Acesso a recursos multimídia que tornam o conteúdo mais interessante. Maior interação entre professores e alunos, inclusive a distância. Desafios. Desigualdade no acesso às tecnologias (nem todos os alunos têm internet ou dispositivos adequados). Formação de professores: muitos ainda não sabem como usar as ferramentas digitais de forma pedagógica. Uso responsável: evitar distrações e ensinar ética digital. Exemplo prático. O professor pode usar o Kahoot para revisar o conteúdo da aula em forma de quiz, ou pedir aos alunos que produzam um vídeo curto explicando um tema estudado.');
    console.log('Resultado da IA:', resultado);
  } catch (err) {
    console.error('Erro:', err.message);
  }
})();